import { Position } from "reactflow";
import Info from "../placeholderData.js/Info";

const nodeDefaults = {
  sourcePosition: Position.Right,
  targetPosition: Position.Left,
  style: {
    fontSize: 20,
    fontWeight: 500,
  },
};

export const initialNodes = [
  {
    id: "Col-0",
    ...nodeDefaults,
    position: { x: -300, y: 250 },
    data: { label: "O" },
    className:"endNode"
  },
  {
    id: "Col-1.1",
    ...nodeDefaults,
    position: { x: 0, y: 0 },
    data: { label: "Research", info: <Info /> },
    className: "research",
  },
  {
    id: "Col-1.2",
    ...nodeDefaults,
    position: { x: 0, y: 125 },
    data: { label: "Planning", info: <Info /> },
    className: "planning",
  },
  {
    id: "Col-1.3",
    ...nodeDefaults,
    position: { x: 0, y: 250 },
    data: { label: "Designing", info: <Info /> },
    className: "designing",
  },
  {
    id: "Col-1.4",
    ...nodeDefaults,
    position: { x: 0, y: 375 },
    data: { label: "Manufacturing", info: <Info /> },
    className: "manufacturing",
  },
  {
    id: "Col-1.5",
    ...nodeDefaults,
    position: { x: 0, y: 500 },
    data: { label: "Sales", info: <Info /> },
    className: "sales",
  },
  {
    id: "Col-2.1",
    ...nodeDefaults,
    position: { x: 300, y: -25 },
    data: { label: "External", info: <Info /> },
    className: "research",
  },
  {
    id: "Col-2.2",
    ...nodeDefaults,
    position: { x: 300, y: 25 },
    data: { label: "Internal", info: <Info /> },
    className: "research",
  },
  {
    id: "Col-2.3",
    ...nodeDefaults,
    position: { x: 300, y: 100 },
    data: { label: "PRD", info: <Info /> },
    className: "planning",
  },
  {
    id: "Col-2.4",
    ...nodeDefaults,
    position: { x: 300, y: 150 },
    data: { label: "Specs", info: <Info /> },
    className: "planning",
  },
  {
    id: "Col-2.5",
    ...nodeDefaults,
    position: { x: 300, y: 225 },
    data: { label: "Hardware", info: <Info /> },
    className: "designing",
  },
  {
    id: "Col-2.6",
    ...nodeDefaults,
    position: { x: 300, y: 275 },
    data: { label: "Software", info: <Info /> },
    className: "designing",
  },
  {
    id: "Col-2.7",
    ...nodeDefaults,
    position: { x: 300, y: 350 },
    data: { label: "Material", info: <Info /> },
    className: "manufacturing",
  },
  {
    id: "Col-2.8",
    ...nodeDefaults,
    position: { x: 300, y: 400 },
    data: { label: "Production", info: <Info /> },
    className: "manufacturing",
  },
  {
    id: "Col-2.9",
    ...nodeDefaults,
    position: { x: 300, y: 475 },
    data: { label: "Online", info: <Info /> },
    className: "sales",
  },
  {
    id: "Col-2.10",
    ...nodeDefaults,
    position: { x: 300, y: 525 },
    data: { label: "Dealership", info: <Info /> },
    className: "sales",
  },
  {
    id: "Col-3.1",
    ...nodeDefaults,
    position: { x: 600, y: -50 },
    data: { label: "B2C", info: <Info /> },
    className: "research",
  },
  {
    id: "Col-3.2",
    ...nodeDefaults,
    position: { x: 600, y: 0 },
    data: { label: "B2C", info: <Info /> },
    className: "research",
  },
  {
    id: "Col-4.1",
    ...nodeDefaults,
    position: { x: 900, y: -150 },
    data: { label: "Online", info: <Info /> },
    className: "research",
  },
  {
    id: "Col-4.2",
    ...nodeDefaults,
    position: { x: 900, y: -100 },
    data: { label: "Interview", info: <Info /> },
    className: "research",
  },
  {
    id: "Col-4.3",
    ...nodeDefaults,
    position: { x: 900, y: -50 },
    data: { label: "Public Data", info: <Info /> },
    className: "research",
  },
  {
    id: "Col-4.4",
    ...nodeDefaults,
    position: { x: 900, y: 0 },
    data: { label: "Health", info: <Info /> },
    className: "research",
  },
  {
    id: "Col-5.1",
    ...nodeDefaults,
    position: { x: 1200, y: -75 },
    data: { label: "O" },
    className:'endNode'
  },
];
